# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-05 09:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('room_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user_read', models.BooleanField(default=True)),
                ('to_user_read', models.BooleanField(default=False)),
                ('from_user_delete', models.BooleanField(default=False)),
                ('to_user_delete', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever_messages', to=settings.AUTH_USER_MODEL, verbose_name=b'reciever')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_messages', to=settings.AUTH_USER_MODEL, verbose_name=b'sender')),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
